"""initial production schema

Revision ID: 2a0778657977
Revises: 
Create Date: 2026-04-28 17:15:23.437932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0778657977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('node_class', sa.Enum('ML_MODEL', 'BUSINESS_RULE_SET', 'API_CONTRACT', 'DB_SCHEMA', 'SCORING_FUNCTION', 'ETL_TRANSFORM', name='node_class_t'), nullable=False),
    sa.Column('version_ref', sa.String(), nullable=False),
    sa.Column('registration_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_validation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lineage_parent', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(), nullable=False),
    sa.Column('criticality', sa.Enum('CRITICAL', 'HIGH', 'STANDARD', name='criticality_t'), nullable=False),
    sa.Column('domain_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('r_s', sa.Float(), nullable=True),
    sa.Column('r_p', sa.Float(), nullable=True),
    sa.Column('r_c', sa.Float(), nullable=True),
    sa.Column('r_r', sa.Float(), nullable=True),
    sa.Column('r_t', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PROVISIONAL', 'IN_REVIEW', 'SUSPENDED', 'RETIRED', name='status_t'), nullable=True),
    sa.Column('ttl_override', sa.Interval(), nullable=True),
    sa.Column('decay_alpha', sa.Float(), nullable=True),
    sa.Column('threshold_provisional', sa.Float(), nullable=True),
    sa.Column('threshold_review', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_team', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escalation_tasks')
    op.drop_table('audit_log')
    op.drop_table('nodes')
    # ### end Alembic commands ###
